require 'grruby/grruby'
require 'grruby/color_constants'
require 'grruby/tasks/gr_function_classes'
require 'rubyplot/scripting_backends/gr/plots'
require 'rubyplot/figure'
require 'rubyplot/scripting_backends/gr/plotspace'
require 'rubyplot/scripting_backends/gr/subplot'
